
baseURL = "https://kirrito-k423.github.io/hugo-theme-topdown"
title = "ACSA Lab"
theme = "topdown"

##### tsj #####
[params.toporg]
name = "USTC"
url = "https://en.ustc.edu.cn/"
[params.logo]
longlogo = "images/acsa_light.png"
[params.pic]
backgroundPic = "images/first.png"
quotePic = "images/winter.jpg"

###  info in first layer bar
[params.barinfo]
text = "Information for:"

[[params.barinfo.main]]
name = "New Students"
link = "publications"

[[params.barinfo.main]]
name = "Faculty & Staff"
link = "publications"

[[params.barinfo.main]]
name = "Administrator"
link = "https://docs.acsalab.com/"

[[params.barinfo.main]]
name = "Alumni"
link = "publications"


[menu] 

[[menu.main]]
name = "People"
url = "people"
weight = 1

[[menu.main]]
name = "Publications"
url = "publications"
weight = 2

[[menu.main]]
name = "Teams"
url = "/teams" # folder
weight = 3

[[menu.main]]
name = "Projects"
url = "/Projects" # folder
weight = 4

[[menu.main]]
name = "News"
url = "/News" # folder
weight = 5

[[menu.main]]
name = "Events"
url = "/Events" # folder
weight = 6

[[menu.main]]
name = "About"
url = "about" # file
weight = 7


[build]
future = "true"
